import React, { useState } from 'react';

export default function AuthorityReview({
  plan,
  sourceHabitation,
  targetSite,
  onReset,
}) {
  const [isApproved, setIsApproved] = useState(false);
  const [approving, setApproving] = useState(false);
  const [officialName, setOfficialName] = useState('Dr. S. K. Patil, IAS (District Collector & DM)');

  const handleApprove = () => {
    setApproving(true);
    setTimeout(() => {
      setIsApproved(true);
      setApproving(false);
    }, 600);
  };

  return (
    <div className="card p-8 border border-slate-200 shadow-sm space-y-6 max-w-3xl mx-auto">
      {/* Official State Seal / Header */}
      <div className="text-center space-y-2 pb-6 border-b border-slate-200">
        <div className="w-12 h-12 rounded-2xl bg-slate-900 text-white flex items-center justify-center text-2xl mx-auto shadow-sm">
          ⚖️
        </div>
        <h2 className="text-xl font-black text-slate-900">
          Relocation Plan Submission & Authority Validation
        </h2>
        <p className="text-xs text-slate-500 max-w-md mx-auto">
          Decision-support protocol under Section 30 of the Disaster Management Act, 2005.
        </p>
      </div>

      {/* Authority Warning / Safeguard Card */}
      <div className="bg-amber-50 border-2 border-amber-300 rounded-2xl p-5 space-y-2 text-xs text-amber-900">
        <div className="flex items-center gap-2">
          <span className="text-lg">⚠️</span>
          <h4 className="font-black text-amber-950 uppercase tracking-wider text-xs">
            AI-Assisted Decision Support Notice
          </h4>
        </div>
        <p className="leading-relaxed">
          This relocation schedule is generated by the Aegis algorithmic optimization engine as a <strong>decision-support recommendation</strong>.
          It does <strong>not</strong> constitute an autonomous executive order. Operational deployment, land requisition,
          and public movement require formal verification and digital authentication by the competent District Magistrate / Incident Commander.
        </p>
      </div>

      {/* Plan Status Banner */}
      <div className="p-4 rounded-xl border flex items-center justify-between bg-slate-50 border-slate-200">
        <div>
          <p className="text-[10px] uppercase font-bold text-slate-400">Current Administrative Status</p>
          <p className={`text-base font-black ${isApproved ? 'text-emerald-700' : 'text-blue-700'}`}>
            {isApproved ? '✓ OFFICIALLY VALIDATED & SIGNED' : '⏳ PENDING AUTHORITY REVIEW'}
          </p>
        </div>
        <span
          className={`px-3 py-1 rounded-full text-xs font-extrabold uppercase ${
            isApproved
              ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
              : 'bg-blue-100 text-blue-800 border border-blue-300'
          }`}
        >
          {isApproved ? 'Validated' : 'Awaiting Sign-off'}
        </span>
      </div>

      {/* Relocation Summary Brief */}
      <div className="bg-white border border-slate-200 rounded-xl p-4 space-y-3 text-xs">
        <h4 className="font-bold text-slate-800 uppercase tracking-wider text-[11px]">
          Plan Dossier Summary
        </h4>
        <div className="grid grid-cols-2 gap-3 text-slate-600">
          <div>
            <span className="text-slate-400 block">Origin Habitation:</span>
            <strong className="text-slate-900">{sourceHabitation?.name} ({sourceHabitation?.district})</strong>
          </div>
          <div>
            <span className="text-slate-400 block">Destination Safe Site:</span>
            <strong className="text-slate-900">{targetSite?.name} ({targetSite?.district})</strong>
          </div>
          <div>
            <span className="text-slate-400 block">Population to Relocate:</span>
            <strong className="text-slate-900">{(sourceHabitation?.population || 1680).toLocaleString()} residents</strong>
          </div>
          <div>
            <span className="text-slate-400 block">Planning Distance:</span>
            <strong className="text-slate-900">{targetSite?.distanceKm || 18} km (Straight-line)</strong>
          </div>
        </div>
      </div>

      {/* Sign-off Action */}
      {!isApproved ? (
        <div className="p-5 bg-blue-50/50 border border-blue-200 rounded-2xl space-y-4">
          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">
              Authorized Signatory Reviewer:
            </label>
            <input
              type="text"
              className="input text-xs w-full py-2"
              value={officialName}
              onChange={(e) => setOfficialName(e.target.value)}
            />
          </div>

          <button
            type="button"
            onClick={handleApprove}
            disabled={approving}
            className="w-full btn btn-primary py-2.5 text-xs font-extrabold shadow-sm flex items-center justify-center gap-2"
          >
            <span>✍️</span> {approving ? 'Authenticating Sign-off...' : 'Simulate Authority Digital Sign-off'}
          </button>
        </div>
      ) : (
        <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-xl text-center text-xs text-emerald-900 space-y-1">
          <p className="font-black text-emerald-950 text-sm">✓ Authorization Complete</p>
          <p>Validated by {officialName} on {new Date().toLocaleDateString('en-IN')}.</p>
          <p className="text-[11px] text-emerald-700">Notified response agencies: Police, NDRF, Health, PWD, Collectorate.</p>
        </div>
      )}

      {/* Reset Button */}
      <div className="text-center pt-2">
        <button
          type="button"
          onClick={onReset}
          className="btn btn-ghost text-xs text-slate-500 hover:text-slate-800"
        >
          ← Plan Another Relocation
        </button>
      </div>
    </div>
  );
}
