// ============================================================
// Aegis Seed Data — Fictional "Narmadanagar District", Madhya Pradesh
// ⚠️  ALL DATA IS SYNTHETIC / DEMO — Not live government data
// Created for SIH26191 prototype demonstration purposes only
// ============================================================

const { calculateRisk } = require('../utils/riskEngine');

const rawVillages = [
  {
    name: 'Rampur Ghat',
    lat: 22.9534,
    lng: 78.1823,
    population: 4820,
    rainfall: 312,
    river_level: 9.4,
    elevation: 28,
    historical_flood_incidents: 8,
    slope: 2.1,
    soil_saturation: 88,
    hospital_count: 1,
    school_count: 2,
    shelter_name: 'Rampur Government Higher Secondary School',
    shelter_capacity: 600,
    shelter_lat: 22.956,
    shelter_lng: 78.185,
  },
  {
    name: 'Kewalpur',
    lat: 22.9812,
    lng: 78.2104,
    population: 3140,
    rainfall: 278,
    river_level: 8.1,
    elevation: 35,
    historical_flood_incidents: 7,
    slope: 3.2,
    soil_saturation: 82,
    hospital_count: 0,
    school_count: 2,
    shelter_name: 'Kewalpur Panchayat Bhavan',
    shelter_capacity: 350,
    shelter_lat: 22.984,
    shelter_lng: 78.213,
  },
  {
    name: 'Sindhupura',
    lat: 23.0145,
    lng: 78.1567,
    population: 6200,
    rainfall: 340,
    river_level: 10.2,
    elevation: 22,
    historical_flood_incidents: 9,
    slope: 1.5,
    soil_saturation: 93,
    hospital_count: 2,
    school_count: 3,
    shelter_name: 'Sindhupura Community Centre',
    shelter_capacity: 900,
    shelter_lat: 23.017,
    shelter_lng: 78.159,
  },
  {
    name: 'Bhairopur',
    lat: 22.9345,
    lng: 78.2456,
    population: 2870,
    rainfall: 195,
    river_level: 5.3,
    elevation: 65,
    historical_flood_incidents: 4,
    slope: 6.4,
    soil_saturation: 62,
    hospital_count: 0,
    school_count: 1,
    shelter_name: 'Bhairopur Primary School',
    shelter_capacity: 280,
    shelter_lat: 22.936,
    shelter_lng: 78.248,
  },
  {
    name: 'Narmadanagar Town',
    lat: 22.9670,
    lng: 78.1200,
    population: 28500,
    rainfall: 220,
    river_level: 6.8,
    elevation: 45,
    historical_flood_incidents: 5,
    slope: 4.1,
    soil_saturation: 71,
    hospital_count: 4,
    school_count: 12,
    shelter_name: 'Narmadanagar District Collectorate Hall',
    shelter_capacity: 3000,
    shelter_lat: 22.969,
    shelter_lng: 78.122,
  },
  {
    name: 'Tilaknagar',
    lat: 23.0320,
    lng: 78.1890,
    population: 5430,
    rainfall: 289,
    river_level: 7.9,
    elevation: 38,
    historical_flood_incidents: 6,
    slope: 3.8,
    soil_saturation: 79,
    hospital_count: 1,
    school_count: 3,
    shelter_name: 'Tilaknagar Sports Complex',
    shelter_capacity: 700,
    shelter_lat: 23.034,
    shelter_lng: 78.191,
  },
  {
    name: 'Dhanwapur',
    lat: 22.8934,
    lng: 78.2670,
    population: 1890,
    rainfall: 112,
    river_level: 2.4,
    elevation: 142,
    historical_flood_incidents: 1,
    slope: 11.2,
    soil_saturation: 38,
    hospital_count: 0,
    school_count: 1,
    shelter_name: 'Dhanwapur Village Hall',
    shelter_capacity: 200,
    shelter_lat: 22.895,
    shelter_lng: 78.269,
  },
  {
    name: 'Sonbhadra Kalan',
    lat: 22.8760,
    lng: 78.1450,
    population: 3670,
    rainfall: 156,
    river_level: 3.8,
    elevation: 98,
    historical_flood_incidents: 2,
    slope: 8.7,
    soil_saturation: 44,
    hospital_count: 1,
    school_count: 2,
    shelter_name: 'Sonbhadra Kalan Government School',
    shelter_capacity: 400,
    shelter_lat: 22.878,
    shelter_lng: 78.147,
  },
  {
    name: 'Pariyapur',
    lat: 23.0534,
    lng: 78.2234,
    population: 2340,
    rainfall: 265,
    river_level: 7.2,
    elevation: 42,
    historical_flood_incidents: 6,
    slope: 4.5,
    soil_saturation: 76,
    hospital_count: 0,
    school_count: 1,
    shelter_name: 'Pariyapur Anganwadi Centre',
    shelter_capacity: 250,
    shelter_lat: 23.055,
    shelter_lng: 78.225,
  },
  {
    name: 'Chandravati',
    lat: 23.0789,
    lng: 78.1345,
    population: 4120,
    rainfall: 178,
    river_level: 4.1,
    elevation: 78,
    historical_flood_incidents: 3,
    slope: 7.2,
    soil_saturation: 52,
    hospital_count: 1,
    school_count: 2,
    shelter_name: 'Chandravati PHC Building',
    shelter_capacity: 450,
    shelter_lat: 23.080,
    shelter_lng: 78.136,
  },
  {
    name: 'Maheshwarpura',
    lat: 22.9123,
    lng: 78.0890,
    population: 5870,
    rainfall: 302,
    river_level: 8.7,
    elevation: 31,
    historical_flood_incidents: 8,
    slope: 2.4,
    soil_saturation: 85,
    hospital_count: 2,
    school_count: 4,
    shelter_name: 'Maheshwarpura ITI Campus',
    shelter_capacity: 800,
    shelter_lat: 22.914,
    shelter_lng: 78.091,
  },
  {
    name: 'Jalgarh',
    lat: 22.8512,
    lng: 78.1978,
    population: 1560,
    rainfall: 88,
    river_level: 1.6,
    elevation: 198,
    historical_flood_incidents: 0,
    slope: 15.3,
    soil_saturation: 28,
    hospital_count: 0,
    school_count: 1,
    shelter_name: 'Jalgarh Gram Panchayat Office',
    shelter_capacity: 150,
    shelter_lat: 22.853,
    shelter_lng: 78.200,
  },
  {
    name: 'Ummedpura',
    lat: 23.0012,
    lng: 78.0534,
    population: 3980,
    rainfall: 234,
    river_level: 6.4,
    elevation: 52,
    historical_flood_incidents: 5,
    slope: 5.1,
    soil_saturation: 68,
    hospital_count: 1,
    school_count: 3,
    shelter_name: 'Ummedpura Degree College Hall',
    shelter_capacity: 550,
    shelter_lat: 23.003,
    shelter_lng: 78.055,
  },
  {
    name: 'Kshipra Teer',
    lat: 23.0245,
    lng: 78.0245,
    population: 2780,
    rainfall: 318,
    river_level: 9.8,
    elevation: 25,
    historical_flood_incidents: 9,
    slope: 1.8,
    soil_saturation: 91,
    hospital_count: 1,
    school_count: 2,
    shelter_name: 'Kshipra Teer Government School Block B',
    shelter_capacity: 420,
    shelter_lat: 23.026,
    shelter_lng: 78.026,
  },
  {
    name: 'Bhavanipur',
    lat: 22.9267,
    lng: 78.0123,
    population: 4450,
    rainfall: 247,
    river_level: 7.1,
    elevation: 48,
    historical_flood_incidents: 6,
    slope: 4.9,
    soil_saturation: 74,
    hospital_count: 1,
    school_count: 3,
    shelter_name: 'Bhavanipur Community Hall',
    shelter_capacity: 600,
    shelter_lat: 22.928,
    shelter_lng: 78.014,
  },
  {
    name: 'Devgadha',
    lat: 23.0890,
    lng: 78.0789,
    population: 1230,
    rainfall: 68,
    river_level: 0.9,
    elevation: 265,
    historical_flood_incidents: 0,
    slope: 18.6,
    soil_saturation: 21,
    hospital_count: 0,
    school_count: 1,
    shelter_name: 'Devgadha Primary School',
    shelter_capacity: 120,
    shelter_lat: 23.090,
    shelter_lng: 78.080,
  },
  {
    name: 'Sunderpur',
    lat: 22.9890,
    lng: 78.2890,
    population: 3320,
    rainfall: 187,
    river_level: 4.8,
    elevation: 72,
    historical_flood_incidents: 3,
    slope: 6.8,
    soil_saturation: 55,
    hospital_count: 1,
    school_count: 2,
    shelter_name: 'Sunderpur Vidyalaya Building',
    shelter_capacity: 380,
    shelter_lat: 22.991,
    shelter_lng: 78.291,
  },
];

const getSeedData = () =>
  rawVillages.map((v) => {
    const { score, category } = calculateRisk(v);
    return {
      ...v,
      district: 'Narmadanagar',
      state: 'Madhya Pradesh',
      risk_score: score,
      risk_category: category,
      data_label: '⚠️ SYNTHETIC/DEMO DATA — Not live government data',
    };
  });

module.exports = getSeedData;
